"""empty message

Revision ID: 4b03e26775e5
Revises: None
Create Date: 2018-06-14 16:13:32.854562

"""

# revision identifiers, used by Alembic.
revision = '4b03e26775e5'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markov_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('model_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markov_models')
    # ### end Alembic commands ###
